/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DelegateTool {
  name: string
  version: string
  description: string
  parameters: string
  author: string
  funcAgent: number
}
export declare class DelegateAgent {
  model: string
  name: string
  tools: Array<DelegateTool>
  constructor(name: string, model: string, tools: Array<DelegateTool>)
  prompt(prompt: string): string
}
