/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DelegateTool {
  name: string
  version: string
  description: string
  parameters: string
  author: string
  handler: (...args: any[]) => any
}
export declare class DelegateAgent {
  model: string
  name: string
  apiKey: string
  baseUrl: string
  preamble: string
  constructor(name: string, model: string, apiKey: string, baseUrl: string, preamble: string)
  promptWithTools(prompt: string, delegateTools: Array<DelegateTool>): string
  prompt(prompt: string): string
}
